name: Docs

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs: {}


jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r docs_requirements.txt
          python setup.py install
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
        with:
          branch: master
          dir_docs: docs/source
          sphinxopts: ''
